[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables are configured in Netlify dashboard

[dev]
# Port, na kterém běží Vite dev server
targetPort = 3000
# Příkaz pro spuštění framework serveru
command = "npm run dev"
# Port Netlify Dev proxy (/.netlify/functions/*)
port = 8888
