-- DOČASNÉ VYPNUTÍ RLS PRO TESTOVÁNÍ
-- Spustit v Supabase SQL Editor - POUZE PRO VÝVOJ!

-- Vypneme RLS na všech tabulkách
ALTER TABLE buildings DISABLE ROW LEVEL SECURITY;
ALTER TABLE members DISABLE ROW LEVEL SECURITY;
ALTER TABLE votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE email_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE global_variables DISABLE ROW LEVEL SECURITY;
ALTER TABLE building_variable_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE observers DISABLE ROW LEVEL SECURITY;
ALTER TABLE voting_tokens DISABLE ROW LEVEL SECURITY;
ALTER TABLE member_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE manual_vote_attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE manual_vote_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE vote_delegations DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE sms_verifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE vote_analytics DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE question_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE proxy_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE attachments DISABLE ROW LEVEL SECURITY;

SELECT 'RLS VYPNUTO - VŠECHNY TABULKY JSOU PŘÍSTUPNÉ! ⚠️ POUZE PRO VÝVOJ!' as status;
